import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

import { useSelector, useDispatch } from 'react-redux'
import { RootState, AppDispatch } from '@/redux/store'
import { fetchProductData } from '@/redux/thunk/products'
import { useEffect } from 'react'
import { Product } from '@/types/types'

export default function Home() {
  const products: Product[] = useSelector((state: RootState) => state.products.products);
  const dispatch = useDispatch<AppDispatch>();

  useEffect(() => {
    // Perform localStorage action
    const item = localStorage.getItem('cart')
  }, [])

  useEffect(() => {
    dispatch(fetchProductData());
  }, [dispatch])
  console.log(products)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {
          products.map((product) => 
            <div key={crypto.randomUUID()}>
              <h1>{product.title}</h1>
            </div>
          )
        }
      </main>
    </>
  )
}
